### ISSUE TITLE
 'Manchester_BenchMark' is missing

### ISSUE THREAD

**Issue by MengjieZhao** [DanielCanteroNTNU/TTB-2D#1]
It seems that 'Manchester_BenchMark' is missing when I execute the default configuration. Only TrainProp_Manchester_BenchMark.m exist but not Manchester_BenchMark.m

**Comment by DanielCanteroNTNU** [comment]
Thank you for pointing that out. A small edit in A02 was done. Now the script uses the correct m file, namely TrainProp_Manchester_BenchMark.m.

**Comment by MengjieZhao** [comment]
thank you very much for the rapid update! it works now!
